# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import Algorithm_pb2 as rpc_dot_Algorithm__pb2


class AlgorithmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/com.treevalue.soundRobot.rpc.Algorithm/Echo',
                request_serializer=rpc_dot_Algorithm__pb2.InputMsg.SerializeToString,
                response_deserializer=rpc_dot_Algorithm__pb2.EchoMsg.FromString,
                )


class AlgorithmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=rpc_dot_Algorithm__pb2.InputMsg.FromString,
                    response_serializer=rpc_dot_Algorithm__pb2.EchoMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.treevalue.soundRobot.rpc.Algorithm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Algorithm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.treevalue.soundRobot.rpc.Algorithm/Echo',
            rpc_dot_Algorithm__pb2.InputMsg.SerializeToString,
            rpc_dot_Algorithm__pb2.EchoMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
