# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/Algorithm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13rpc/Algorithm.proto\x12\x1c\x63om.treevalue.soundRobot.rpc\"\x19\n\x08InputMsg\x12\r\n\x05input\x18\x01 \x01(\t\"\x19\n\x07\x45\x63hoMsg\x12\x0e\n\x06output\x18\x01 \x01(\t2d\n\tAlgorithm\x12W\n\x04\x45\x63ho\x12&.com.treevalue.soundRobot.rpc.InputMsg\x1a%.com.treevalue.soundRobot.rpc.EchoMsg\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.Algorithm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTMSG']._serialized_start=53
  _globals['_INPUTMSG']._serialized_end=78
  _globals['_ECHOMSG']._serialized_start=80
  _globals['_ECHOMSG']._serialized_end=105
  _globals['_ALGORITHM']._serialized_start=107
  _globals['_ALGORITHM']._serialized_end=207
# @@protoc_insertion_point(module_scope)
